#! /usr/bin/bash
java -jar fitnesse.jar -c  "HttpTestSuite.ResponseTestSuite.SimpleGet?test&format=text"
java -jar fitnesse.jar -c  "HttpTestSuite.ResponseTestSuite.FourOhFour?test&format=text"
java -jar fitnesse.jar -c  "HttpTestSuite.ResponseTestSuite.SimplePut?test&format=text"


